In [3]:
#q1
import math
x=7.9
print(math.floor(x))
x=7.1
print(math.ceil(x))
x=25
print(math.sqrt(x))
a=48
b=18
print(math.gcd(a,b))

7
8
5.0
6


In [6]:
import statistics
import math
data=[4,9,16,25]
mean_val=statistics.mean(data)
sqrt_mean=math.sqrt(mean_val)
print(mean_val)
print(sqrt_mean)

13.5
3.6742346141747673


In [7]:
import numpy as np
arr=np.array([3.7,4.2,5.9])
print(np.floor(arr))
print(np.ceil(arr))
arr2=np.array([4,16,25])
print(np.sqrt(arr2))
a=np.array([12,18,27])
b=np.array([6,9,3])
print(np.gcd(a,b))

[3. 4. 5.]
[4. 5. 6.]
[2. 4. 5.]
[6 9 3]


In [3]:
import scipy
import numpy as np 
print(np.gcd(48, 18))

6


In [4]:
import numpy as np
from scipy import linalg
x=np.array([9,16,25])
print(np.sqrt(x))

[3. 4. 5.]


In [6]:
#q2
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.sum())
print(arr.mean())
arr2=np.array([9,3,6,1])
arr2.sort()
print(arr2)
angles=np.array([0,np.pi/2,np.pi])
print(np.sin(angles))
print(arr.max())
print(arr.min())
print(arr.reshape(3,2))

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int32
21
3.5
[1 3 6 9]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
6
1
[[1 2]
 [3 4]
 [5 6]]


In [9]:
#q3
import numpy as np
A=np.array([[1,2],[3,4]])
det_A=np.linalg.det(A)
print(det_A)
A=np.array([[2,0],[0,3]])
eigenvalues,eigenvectors=np.linalg.eig(A)
print("Eigenvalues")
print(eigenvalues)
print(eigenvectors)

-2.0000000000000004
Eigenvalues
[2. 3.]
[[1. 0.]
 [0. 1.]]


In [1]:
import numpy as np
lst=[1,2,3,4,5,6]
arr1d=np.array(lst)
print(arr1d)
print(arr1d.ndim)
arr2d=arr1d.reshape(2,3)
print(arr2d)
print(arr2d.ndim)
arr3d=arr1d.reshape(1,2,3)
print(arr3d)
print(arr3d.ndim)

[1 2 3 4 5 6]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]]]
3


In [5]:
#q5
import numpy as np
a=np.zeros((2,2))
b=np.ones((2,2))
c=np.eye(2)
m=np.array([[1,2],[3,4]])
print(a)
print(b)
print(c)
print(m)
print(m.T)
print(np.linalg.det(m))

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0.]
 [0. 1.]]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
-2.0000000000000004


In [6]:
#q6
import numpy as np
from scipy import linalg
a=np.array([[1,2],[3,4]])
det_a=linalg.det(a)
print(det_a)

-2.0


In [7]:
#q7
import numpy as np
from scipy import linalg
a=np.array([[2,0],[0,3]])
eigen_values,eigen_vectors=linalg.eig(a)
print(eigen_values)
print(eigen_vectors)

[2.+0.j 3.+0.j]
[[1. 0.]
 [0. 1.]]
